# Generated by Django 4.1.2 on 2022-11-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
