# Generated by Django 4.1.2 on 2022-11-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
